# logging 레벨 설정
logging:
  level:
    root: INFO
    sql: ERROR
# Overloaded POST 사용
spring:
  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:tcp://localhost/~/cac-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.naver.com
    port: 465
    username: { Sender ID } # !! 외부 및 다른 사람에게 노출되지 않도로 주의 !!
    password: { Sender Password } # !! 외부 및 다른 사람에게 노출되지 않도로 주의 !!
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

## session
#server:
#  servlet:
#    session:
#      timeout: 10m # 기본이 30분이고 최소는 1분입니다.