package com.proejct.ClassActionClaim.domain;

import com.proejct.ClassActionClaim.domain.baseEntities.User;
import lombok.Getter;
import javax.persistence.*;
import javax.validation.constraints.Email;

/**
 * Student Entity
 *
 * id : AutoGenerated Id
 * username: Student Assigned Username; Unique
 * password
 * studentEmail: Must be an email ending with @sju.ac.kr; suffix for student emails attending Sejong University
 *
 */
@Entity
@Getter
public class Student extends User {

    @Column(nullable = false)
    @Email
    private String studentEmail;

    public Student(String username, String password, String studentEmail) {
        super(username, password, "ROLE_STUDENT");
        this.studentEmail = studentEmail;
    }

    public static Student of(String username, String password, String studentEmail) {
        return new Student(username, password, studentEmail);
    }

}
