package com.proejct.ClassActionClaim.domain;

import com.proejct.ClassActionClaim.domain.baseEntities.DateTimeEntity;
import lombok.Getter;

import javax.persistence.*;

/**
 * Student Entity
 *
 * id : AutoGenerated Id
 * username: Student Assigned Username; Unique
 * password
 * schoolEmail: Must be an email ending with @sju.ac.kr; suffix for student emails attending Sejong University
 *
 */

@Entity
@Getter
public class Student extends DateTimeEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "studentId")
    public Long id;

    @Column(unique = true, nullable = false)
    public String username;

    @Column(nullable = false)
    public String password;

    @Column(unique = true, nullable = false)
    public String schoolEmail;

}
